services:
  client:
    build:
      context: ./side-front
      dockerfile: Dockerfile
    volumes:
      - ./side-front/dist:/usr/share/nginx/html
    depends_on:
      - server

  server:
    build:
      context: ./side-api
      dockerfile: Dockerfile
    expose:
      - "3000"

  nginx:
    image: nginx:1.26.3
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./side-front/dist:/usr/share/nginx/html
    depends_on:
      - server