services:
  client:
    build:
      context: ./side-front
      dockerfile: Dockerfile
    depends_on:
      - server

  server:
    build:
      context: ./side-api
      dockerfile: Dockerfile
    expose:
      - "3000"
    restart: always

  nginx:
    build:
      context: ./side-front
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - server

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - nginx
    command: tunnel --url http://nginx:80