services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    expose:
      - "3000"
    restart: always
    volumes:
      - ./server/data:/app/data
      - ./server/cookies:/app/cookies
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - server
    command: tunnel --url http://server:3000